//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

[Serializable]
public class CharacterClass : ScriptableObject
{
	public float expertisePerLevel = 1f;
	public float hitpointsPerLevel = 10f;
	public string className;

	/// <summary>
	/// Calculates the hitpoints.
	/// </summary>
	/// <returns>The hitpoints.</returns>
	/// <param name="character">Character.</param>
	public float CalculateHitpoints(Character character) {
		return character.level * hitpointsPerLevel;
	}

	/// <summary>
	/// Calculates the expertise.
	/// </summary>
	/// <returns>The expertise.</returns>
	/// <param name="character">Character.</param>
	public float CalculateExpertise(Character character) {
		return expertisePerLevel * character.level;
	}
}