// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public class CombatNodeBuilder
{
	private CombatNodeFactory mFactory;

	private int mWeaponIndex;
	

	public CombatNodeBuilder (CombatNodeFactory factory)
	{
		this.mFactory = factory;
		this.mWeaponIndex = 0;
	}

	/// <summary>
	/// Sets the index of the weapon. This is set to 0 by default.
	/// </summary>
	/// <param name="weaponIndex">Weapon index.</param>
	public void SetWeaponIndex(int weaponIndex) {
		mWeaponIndex = weaponIndex;
	}

	public CompositeCombatModifierNode Build(SkillCombatNode skillCombatNode) {
		// build composite for character
		CompositeCombatModifierNode rootNode = new CompositeCombatModifierNode ();
		// child node
		rootNode.AddNode (mFactory.CreateCharacterNode());
		rootNode.AddNode (mFactory.CreateWeaponConfigNode (mWeaponIndex));
		rootNode.AddNode (skillCombatNode);

		// TODO iterate through buffs
		return rootNode;
	}
}
