//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class CompositeCombatModifierNode : IOffensiveCombatNode
{
	private List<IOffensiveCombatNode> mChildren;

	public CompositeCombatModifierNode ()
	{
		mChildren = new List<IOffensiveCombatNode>();
	}

	public void AddNode(IOffensiveCombatNode combatNode) {
		mChildren.Add (combatNode);
	}

	public float GetPropertyAdd(OffensiveCombatNodeProperty property) {

		float total = 0;
		foreach(IOffensiveCombatNode mod in mChildren) {
			total += mod.GetPropertyAdd(property);
		}
		return total;

	}

	public float GetPropertyMultiply(OffensiveCombatNodeProperty property) {

		float total = 1;
		foreach(IOffensiveCombatNode mod in mChildren) {
			total *= mod.GetPropertyMultiply(property);
		}
		return total;

	}


}


