// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public enum DefensiveCombatNodeProperty
{
	// common
	REFLEX,
	CRIT_DEFENSE,
	RESIST_SLASH,
	RESIST_CRUSH,
	RESIST_PIERCE,
	RESIST_DARK,
	RESIST_LIGHT,
	RESIST_WIND,
	RESIST_EARTH,
	RESIST_WATER,
	RESIST_FIRE,
	COUNT
}

