//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

/// <summary>
/// Defensive configurable combat node. Best used when inherited
/// </summary>
public class DefensiveConfigurableCombatNode : IDefensiveCombatNode
{

	protected float[] mPropertyAdd;
	protected float[] mPropertyMultiply;

	public DefensiveConfigurableCombatNode ()
	{
		// resists
		mPropertyAdd = new float[(int)DefensiveCombatNodeProperty.COUNT];
		mPropertyMultiply = new float[(int)DefensiveCombatNodeProperty.COUNT];
		for (int i=0; i < (int)DefensiveCombatNodeProperty.COUNT; i++) {
			mPropertyMultiply[i] = 1f;
		}
	}

	public float GetPropertyAdd (DefensiveCombatNodeProperty property)
	{
		return mPropertyAdd [(int)property];
	}

	public float GetPropertyMultiply (DefensiveCombatNodeProperty property)
	{
		return mPropertyMultiply [(int)property];
	}
}


