//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public interface IOffensiveGeneralCombatNode
{
	float totalDamageAdd {
		get;
	}
	
	float totalDamageMultiply {
		get;
	}
	
	float critChanceAdd {
		get;
	}
	
	float critChanceMultiply {
		get;
	}

	float statSTRAdd {
		get;
	}

	float statSTRMultiply {
		get;
	}

	float statVITAdd {
		get;
	}

	float statVITMultiply {
		get;
	}

	float statDEXAdd {
		get;
	}

	float statDEXMultiply {
		get;
	}

	float statAGIAdd {
		get;
	}

	float statAGIMultiply {
		get;
	}

	float statINTAdd {
		get;
	}

	float statINTMultiply {
		get;
	}

	float statWISAdd {
		get;
	}

	float statWISMultiply {
		get;
	}

	float statLUCKAdd {
		get;
	}

	float statLUCKMultiply {
		get;
	}
}


