// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class CombatNodeFactory
{
	private BattleEntity mEntity;

	public BattleEntity entity {
		get { return mEntity; }
	}

	private CharacterCombatNode mCachedCharacterNode;

	public CombatNodeFactory (BattleEntity entity)
	{
		mEntity = entity;
	}

	public ICombatNode CreateWeaponConfigNode(int equipedWeaponIndex) {
		IWeapon weapon = mEntity.equipedWeapons [equipedWeaponIndex];
		return CreateWeaponConfigNode (weapon);
	}

	public ICombatNode CreateWeaponConfigNode(IWeapon config) {
		return new WeaponCombatNode(config);
	}

	public ICombatNode CreateCharacterNode() {
		if (mCachedCharacterNode == null) {
			mCachedCharacterNode = new CharacterCombatNode(mEntity.character);
		}
		return mCachedCharacterNode;
	}
}

