// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class CombatResolver
{
	private BattleEntity mEntity;
	private ICombatNode mRootNode;

	public CombatResolver (BattleEntity entity) : this(entity, entity.CreateDefaultCombatNode()) {
	}

	public CombatResolver (BattleEntity entity, ICombatNode rootNode)
	{
		mRootNode = rootNode;
		mEntity = entity;
	}

	public BattleEntity entity {
		get { return mEntity; }
	}

	public float GetProperty(CombatProperty property) {
		float ret = mRootNode.GetPropertyAdd (property);
		ret *= mRootNode.GetPropertyMultiply (property);
		return ret;
	}

	public float GetAccuracy() {
		return GetProperty(CombatProperty.ACCURACY);
	}

	public float GetPhysicalDamage() {
		float totalDamage = GetProperty (CombatProperty.TOTAL_DAMAGE);

		float strScale = GetProperty (CombatProperty.MAG_SCALE_STR);
		if (strScale >= 0) {

		}
		return totalDamage;
	}

	public float GetMagicalDamage() {
		float totalDamage = GetProperty (CombatProperty.TOTAL_DAMAGE);
		return totalDamage;
	}

	public float GetPhysicalPower() {
		return GetProperty(CombatProperty.POWER_PHYSICAL);
	}

	public float GetMagicalPower() {
		return GetProperty(CombatProperty.POWER_MAGIC);
	}

	/// <summary>
	/// Gets the crit chance.
	/// </summary>
	/// <returns>The crit chance.</returns>
	public float GetCritChance() {
		return GetProperty(CombatProperty.CRIT_CHANCE);
	}

	/// <summary>
	/// Gets the reflex.
	/// </summary>
	/// <returns>The reflex.</returns>
	public float GetReflex() {
		return GetProperty(CombatProperty.REFLEX);
	}
	
	/// <summary>
	/// Gets the crit defense.
	/// </summary>
	/// <returns>The crit defense.</returns>
	public float GetCritDefense() {
		return GetProperty(CombatProperty.CRIT_DEFENSE);
	}
	
	/// <summary>
	/// Gets the resist.
	/// </summary>
	/// <returns>The resist.</returns>
	/// <param name="dmgType">Dmg type.</param>
	public float GetResist(DamageType dmgType) {
		CombatProperty prop;
		switch (dmgType) {
		case DamageType.SLASH:
			prop = CombatProperty.RESIST_SLASH;
			break;
		case DamageType.CRUSH:
			prop = CombatProperty.RESIST_CRUSH;
			break;
		case DamageType.PIERCE:
			prop = CombatProperty.RESIST_PIERCE;
			break;
		case DamageType.DARK:
			prop = CombatProperty.RESIST_DARK;
			break;
		case DamageType.LIGHT:
			prop = CombatProperty.RESIST_LIGHT;
			break;
		case DamageType.WIND:
			prop = CombatProperty.RESIST_WIND;
			break;
		case DamageType.EARTH:
			prop = CombatProperty.RESIST_EARTH;
			break;
		case DamageType.WATER:
			prop = CombatProperty.RESIST_WATER;
			break;
		case DamageType.FIRE:
		default:
			prop = CombatProperty.RESIST_FIRE;
			break;
		}
		
		return GetProperty (prop);
	}
}
