// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public class CombatNodeBuilder
{
	private CombatNodeFactory mFactory;

	private int mWeaponIndex;
	private SkillCombatNode mSkillCombatNode;

	public CombatNodeBuilder (CombatNodeFactory factory)
	{
		this.mFactory = factory;
		this.mWeaponIndex = 0;
	}

	/// <summary>
	/// Sets the index of the weapon. This is set to 0 by default.
	/// </summary>
	/// <param name="weaponIndex">Weapon index.</param>
	public CombatNodeBuilder SetWeaponIndex(int weaponIndex) {
		mWeaponIndex = weaponIndex;
		return this;
	}

	public CombatNodeBuilder SetSkillCombatNode(SkillCombatNode skillCombatNode) {
		mSkillCombatNode = skillCombatNode;
		return this;
	}

	public CompositeCombatNode Build() {
		// build composite for character
		CompositeCombatNode rootNode = new CompositeCombatNode ();
		// child node
		rootNode.AddNode (mFactory.CreateCharacterNode());
		rootNode.AddNode (mFactory.CreateWeaponConfigNode (mWeaponIndex));
		if (mSkillCombatNode != null) {
			rootNode.AddNode (mSkillCombatNode);
		}

		// TODO iterate through buffs and equipment
		return rootNode;
	}
}
