//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ConfigurableCombatNode : ICombatNode
{
	protected float [] mPropertyAdd;
	protected float [] mPropertyMultiply;

	public ConfigurableCombatNode ()
	{
		mPropertyAdd = new float[(int)CombatPropertyType.COUNT];
		mPropertyMultiply = new float[(int)CombatPropertyType.COUNT];

		for(int i=0; i < (int)CombatPropertyType.COUNT; i++) {
			mPropertyMultiply[i] = 1f;
		}
	}

	public float GetPropertyAdd (CombatPropertyType property)
	{
		return mPropertyAdd[(int)property];
	}

	public float GetPropertyMultiply (CombatPropertyType property)
	{
		return mPropertyMultiply[(int)property];
	}

	/// <summary>
	/// Load the specified combatProperties.
	/// </summary>
	/// <param name="combatProperties">Combat properties.</param>
	public void Load(CombatProperty [] combatProperties) {
		if(combatProperties == null) {
			Debug.Log("Failed to load combatProperties, null: " + this);
			return;
		}

		foreach(CombatProperty property in combatProperties) {
			this.mPropertyAdd[(int)property.propertyType] = property.add;
			this.mPropertyMultiply[(int)property.propertyType] = property.multiply;
		}
	}

	public void Load(ResistProperties resists) {
		if(resists != null) {
			mPropertyAdd[(int)CombatPropertyType.RESIST_CRUSH] = resists.crush;
			mPropertyAdd[(int)CombatPropertyType.RESIST_SLASH] = resists.slash;
			mPropertyAdd[(int)CombatPropertyType.RESIST_PIERCE] = resists.pierce;
			mPropertyAdd[(int)CombatPropertyType.RESIST_LIGHT] = resists.light;
			mPropertyAdd[(int)CombatPropertyType.RESIST_DARK] = resists.dark;
			mPropertyAdd[(int)CombatPropertyType.RESIST_EARTH] = resists.earth;
			mPropertyAdd[(int)CombatPropertyType.RESIST_WIND] = resists.wind;
			mPropertyAdd[(int)CombatPropertyType.RESIST_FIRE] = resists.fire;
			mPropertyAdd[(int)CombatPropertyType.RESIST_WATER] = resists.water;
		}
	}
}


