//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class WeaponConfigCombatNode : ConfigurableCombatNode
{
	public WeaponConfigCombatNode(WeaponData weaponConfig) : base() {
		// TODO put in magical augments
		ReadGeneralModifiers(weaponConfig.generalModifiers);
		ReadPhysicalModifiers(weaponConfig.physicalModifiers);
		ReadStatModifiers(weaponConfig.statModifiers);
	}
}

