//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class WeaponCombatNode : EquipmentCombatNode
{
    private IWeapon mWeapon;
	public WeaponCombatNode(IWeapon weapon) : base(weapon) {
        mWeapon = weapon;
	}

    public AttributeVector AttributeScalar {
        get { return mWeapon.AttributeScaling; }
    }

    public ElementVector DamageMin {
        get { return mWeapon.DamageMin; }
    }

    public ElementVector DamageMax {
        get { return mWeapon.DamageMax; }
    }
}

