//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;

[Serializable]
public class AISkillRule
{
	[SerializeField]
	private CombatSkillConfig mSkill;

	[SerializeField]
	private Condition mCondition;

	[SerializeField]
	private float mValue;


	private enum Condition {
		IS_LESS_THAN,
		IS_GREATER_THAN
	}
}


