// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public abstract class AbstractCombatOperation : ICombatOperation
{
	/// <summary>
	/// Executes the damage against target entity.
	/// </summary>
	/// <param name="damage">Damage.</param>
	/// <param name="destEntity">Destination entity.</param>
	protected void ExecuteDamage (float damage, BattleEntity destEntity)
	{
		damage = Mathf.Ceil(damage);
		if(destEntity.character.curHP <= 0) {
			return; // character is dead, no need to add more death
		}
		destEntity.character.curHP -= damage;
	}

	public abstract IBattleEvent Execute (CombatResolver srcResolver, CombatResolver destResolver);
}

