// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

public abstract class AbstractCombatOperation : ICombatOperation
{

	protected const float CRIT_MULTIPLIER_LOW = 0.5f;
	protected const float CRIT_MULTIPLIER_HIGH = 0.8f;

	/// <summary>
	/// Executes the damage against target entity.
	/// </summary>
	/// <param name="damage">Damage.</param>
	/// <param name="destEntity">Destination entity.</param>
	protected void ExecuteDamage (float damage, BattleEntity destEntity)
	{
		damage = Mathf.Ceil(damage);
		if(destEntity.currentHP <= 0) {
			return; // character is dead, no need to add more death
		}
		destEntity.currentHP -= damage;
	}

	protected void ExecuteHealing(float heal, BattleEntity destEntity) {
		heal = Mathf.Ceil(heal);
		// heal but cap the hitpoints to the max
		destEntity.currentHP = Mathf.Min (destEntity.currentHP + heal, destEntity.maxHP);
	}

	public abstract IBattleEvent Execute (CombatResolver srcResolver, CombatResolver destResolver);
}

