//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class BattleEventManager
{
	public IBattleEventListener battleEventListener {
		get;
		set;
	}

	public BattleEventManager ()
	{
	}
	

	public void GeneratePhysicalEvent(BattleEntity src, BattleEntity dest, 
	                                BattleActionPhysical action,                                   	
	                                CombatStatusEffectList options,
	                                DamageType damageType,
	                                ICombatNode physicalCombatNode) {
		CombatResolver offensiveResolver = new CombatResolver (physicalCombatNode);
		PhysicalAttackOperation attackEvent = new PhysicalAttackOperation(src, dest, action, damageType, offensiveResolver);
		NotifyEvent (attackEvent);
		PostDamageEvent(attackEvent);

		// check to see if we hit for any status effects
		//if(!attackEvent.isEvaded) {
		//	ApplyEffects(options.destStatusEffects, dest);
		//	ApplyEffects(options.srcStatusEffects, src);
		//}
	}

	public void GenerateMagicalEvent(BattleEntity src, BattleEntity dest, 
	                               BattleActionMagical action, 
	                               CombatStatusEffectList options,
	                                 DamageType damageType,
	                                 ICombatNode magicalCombatNode) {
		// TODO, move src, dest to resolver type actions exposing raw battle entity
		// remove battle action from event
		// damage type ok
		CombatResolver offensiveResolver = new CombatResolver (magicalCombatNode);
		CombatResolver defensiveResolver = new CombatResolver (dest.CreateCombatNodeBuilder().Build());
		MagicAttackOperation magicOperation = new MagicAttackOperation (src, dest, action, damageType);
		magicOperation.Execute (offensiveResolver, defensiveResolver);

		NotifyEvent(magicEvent);
		PostDamageEvent(magicEvent);
	}

	public void GeneratePositiveEvent(BattleEntity src, BattleEntity dest, 
	                                 BattleActionPositive action, 
	                                 CombatStatusEffectList options) {
		
	}

	/// <summary>
	/// Applies the effects.
	/// </summary>
	/// <param name="effects">Effects.</param>
	/// <param name="targetEntity">Target entity.</param>
	private void ApplyEffects(IStatusEffect [] effects, BattleEntity targetEntity) {
		if(effects != null) {
			foreach(IStatusEffect effect in effects) {
				targetEntity.ApplyStatusEffect(effect);
			}
		}
	}

	/// <summary>
	/// Notifies the event.
	/// </summary>
	/// <param name="battleEvent">Battle event.</param>
	private void NotifyEvent(IBattleEvent battleEvent) {
		if(battleEventListener != null) {
			battleEventListener.OnBattleEvent(battleEvent);
		}
	}

	// calculate and apply damage state (see if they are dead or not)
	private void PostDamageEvent(IBattleDamageEvent dmgEvent) {
		BattleEntity destEntity = dmgEvent.destEntity;
		// if character died, notify death event
		if(destEntity.character.curHP <= 0) {
			destEntity.character.curHP = 0;
			BattleEventDeath deathEvent = new BattleEventDeath(destEntity);
			NotifyEvent(deathEvent);
		}

	}		
}
