//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class CombatStatusEffectList
{
	public static readonly CombatStatusEffectList EMPTY = new CombatStatusEffectList();
	
	public StatusEffectRule[] statusEffects {
				get;
				private set;
	}
	
	private CombatStatusEffectList () {	}

	/// <summary>
	/// Builder this instance.
	/// </summary>
	public static StatusEffectBuilder Builder() {
		return new StatusEffectBuilder();
	}

	public class StatusEffectBuilder {
		private List<StatusEffectRule> statusEffectEvents = null;

		public StatusEffectBuilder AddStatusEffect(IStatusEffectExecutor effect, BattleEntity target, StatusEffectRule.StatusEffectHitPredicate rule) {
			if(statusEffectEvents == null) {
				statusEffectEvents = new List<StatusEffectRule>();
			}
			statusEffectEvents.Add(new StatusEffectRule(effect, target, rule));
			return this;
		}

		public CombatStatusEffectList Build() {
			CombatStatusEffectList ret = new CombatStatusEffectList();
			if(statusEffectEvents != null) {
				ret.statusEffects = statusEffectEvents.ToArray();
			}
			return ret;
		}
	}
}
