//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public interface ICombatOperation
{
	/// <summary>
	/// Execute the specified srcResolver and destResolver.
	/// </summary>
	/// <param name="srcResolver">Source resolver.</param>
	/// <param name="destResolver">Destination resolver.</param>
	void Execute(CombatResolver srcResolver, CombatResolver destResolver);
}

