//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class BattleAttackEvent : IBattleDamageEvent
{
	BattleEntity mSrcEntity;
	BattleEntity mDestEntity;
	float mTotalDamage;

	public BattleAttackEvent (BattleEntity srcEntity, BattleEntity destEntity, float totalDamage) 
	{
		this.mSrcEntity = srcEntity;
		this.mDestEntity = destEntity;
		this.mTotalDamage = totalDamage;
	}

	public BattleEntity srcEntity {
		get {
			return srcEntity;
		}
	}

	public BattleEventType eventType {
		get {
			return BattleEventType.MOVE;
		}
	}

}


