//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class DeathEvent : IBattleEvent
{
	private BattleEntity mSrcEntity;

	public DeathEvent (BattleEntity entity)
	{
		mSrcEntity = entity;
	}

	public BattleEntity srcEntity {
		get {
			return mSrcEntity;
		}
	}

	public BattleEventType eventType {
		get {
			return BattleEventType.DEATH;
		}
	}

	public string eventText {
		get {
			return string.Format("{0} has died.", mSrcEntity.character.displayName);
		}
	}

	public override string ToString ()
	{
		return string.Format ("[BattleEventDeath: srcEntity={0}, eventType={1}, eventText={2}]", srcEntity, eventType, eventText);
	}
}
