// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class NonDamageEvent : IBattleEvent
{
	private BattleEntity mSrcEntity;
	private BattleEntity mDestEntity;

	public NonDamageEvent (BattleEntity srcEntity, BattleEntity destEntity) 
	{

	}

	public BattleEntity srcEntity {
		get {
			return mSrcEntity;
		}
	}

	public BattleEntity destEntity {
		get {
			return mDestEntity;
		}
	}

	public BattleEventType eventType {
		get {
			return BattleEventType.NON_DAMAGE;
		}
	}
}

