//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

[Serializable]
public class Weapon : ScriptableObject
{
	public string weaponName;
	public float baseDamage;
	public float strModifier;
	public float agiModifier;
	public float dexModifier;
	public float intModifier;
	public float wisModifier;

	public DamageType dmgType;
	public WeaponType weaponType;

	public Texture2D icon;


	/// <summary>
	/// Calculates the attack. based on modifiers and base damasge
	/// </summary>
	/// <returns>The attack.</returns>
	/// <param name="character">Character.</param>
	public float CalculateAttack(Character character) {
		float atk = baseDamage;
		atk += strModifier * character.strength;
		atk += agiModifier * character.agility;
		atk += dexModifier * character.dexerity;
		atk += intModifier * character.inteligence;
		atk += wisModifier * character.wisdom;
		return atk;
	}
}