//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class TargetConditionFilter
{
	public static bool PassesFilter(BattleEntity entity, TargetFilter filter) {
		switch(filter) {
		case TargetFilter.REQUIRE_ALIVE:
			return entity.character.curHP > 0;
		case TargetFilter.REQUIRE_BLIND:
			// TODO
			return true;
		case TargetFilter.REQUIRE_DEAD:
			return entity.character.curHP <= 0;
		}
		return true;
	}
}

