//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

[Serializable]
public class ElementProperties
{
	// physical
	public float slash;
	public float pierce;
	public float crush;

	public float dark;
	public float light;
	public float wind;
	public float earth;
	public float fire;
	public float water;
}


