//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class MagicalCombatSkillSO : CombatSkillSO
{
	[SerializeField]
	private MagicalOffensiveModifier [] mOffensiveModifiers = null;
	public MagicalOffensiveModifier [] offensiveModifiers { get { return mOffensiveModifiers; } }
	
	public override CombatSkillType combatSkillType {
		get {
			return CombatSkillType.MAGICAL;
		}
	}

	public override CombatSkill CreateCombatSkill (int level)
	{
		return new MagicalCombatSkill(this, level);
	}	

	void OnEnable() {
		mModifierMap = new Dictionary<MagicalOffensiveModifierType, float>();
		foreach(MagicalOffensiveModifier mod in mOffensiveModifiers) {
			mModifierMap[mod.type] = mod.modValue;
		}
	}

	private Dictionary<MagicalOffensiveModifierType, float> mModifierMap;


	public float this[MagicalOffensiveModifierType type] {
		get { 
			if(mModifierMap.ContainsKey(type)) {
				return mModifierMap[type]; 
			}
			return 0f;
		}
	}
}

