//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class PositiveCombatSkill : CombatSkill
{
	public PositiveCombatSkill(CombatSkillConfig config, int level) : base (config, level) {
	}

	public PositiveCombatSkillConfig positiveCombatSkillConfig {
		get { return (PositiveCombatSkillConfig) mSkillConfig; } 
	}

	public float this[PositiveOffensiveModifierType type] {
		get { return positiveCombatSkillConfig[type]; }
	}
}

