// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public abstract class AbstractBattleDamageEvent : IBattleDamageEvent
{
	protected void ExecuteDamage ()
	{
		if(destEntity.character.curHP <= 0) {
			return; // character is dead, no need to add more death
		}
		destEntity.character.curHP -= totalDamage;
	}

	public abstract void Execute ();

	public abstract BattleEntity destEntity {
				get;
	}

	public abstract float totalDamage {
				get;
	}

	public abstract BattleEntity srcEntity {
				get;
	}

	public abstract BattleEventType eventType {
				get;
	}

	public abstract string eventText {
				get;
	}
}

