//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class BattleEventManager
{
	public BattleEventManager ()
	{
	}

	public void DoAttack(BattleEntity src, BattleEntity dest, BattleAction action, OffensiveModifier [] modifiers) {
		Character character = src.character;

		Weapon weapon = character.mainHandWeapon;



		if(modifiers != null) {

		}

		float dmg = weapon.weaponConfig.baseDamage;
		float rolledDmg = UnityEngine.Random.Range(dmg * 0.8f, dmg * 1.2f); // tmp


	}
}
