//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class BattleEventStatusEffects
{
	public static readonly BattleEventStatusEffects EMPTY = new BattleEventStatusEffects();

	private IStatusEffect[] mDestStatusEffects = null;
	public IStatusEffect[] destStatusEffects {
		get { return mDestStatusEffects; }
	}

	private IStatusEffect[] mSrcStatusEffects = null;
	public IStatusEffect[] srcStatusEffects {
		get { return mSrcStatusEffects; }
	}

	private BattleEventStatusEffects () {	}

	/// <summary>
	/// Builder this instance.
	/// </summary>
	public static StatusEffectBuilder Builder() {
		return new StatusEffectBuilder();
	}

	public class StatusEffectBuilder {
		private List<IStatusEffect> mSrcEffects = null;
		private List<IStatusEffect> mDestEffects = null;

		public StatusEffectBuilder AddSourceStatusEffect(IStatusEffect effect) {
			if(mSrcEffects == null) {
				mSrcEffects = new List<IStatusEffect>();
			}
			mSrcEffects.Add(effect);
			return this;
		}

		public StatusEffectBuilder AddDestStatusEffect(IStatusEffect effect) {
			if(mDestEffects == null) {
				mDestEffects = new List<IStatusEffect>();
			}
			mDestEffects.Add(effect);
			return this;
		}

		public BattleEventStatusEffects Build() {
			BattleEventStatusEffects parameter = new BattleEventStatusEffects();
			if(mSrcEffects != null) {
				parameter.mSrcStatusEffects = mSrcEffects.ToArray();
			}

			if(mDestEffects != null) {
				parameter.mDestStatusEffects = mDestEffects.ToArray();
			}

			return parameter;
		}
	}
}
