//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class BattleCombatEvent
{
	private BattleEntity mSrcEntity;
	private BattleEntity [] mDestEntities;

	public BattleCombatEvent (BattleEntity src, BattleEntity dest) : this(src, new BattleEntity[]{dest})
	{
	}

	public BattleCombatEvent(BattleEntity src, BattleEntity[] dest) {
		this.mSrcEntity = src;
		this.mDestEntities = dest;
	}

	public void Execute() {

	}
}

