//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class BattleEventDeath : IBattleEvent
{
	private BattleEntity mSrcEntity;

	public BattleEventDeath (BattleEntity entity)
	{
		mSrcEntity = entity;
	}

	public BattleEntity srcEntity {
		get {
			return mSrcEntity;
		}
	}

	public BattleEventType eventType {
		get {
			return BattleEventType.DEATH;
		}
	}

	public string eventText {
		get {
			return string.Format("{0} has died.", mSrcEntity.character.displayName);
		}
	}

	public void Execute ()
	{
		// perhaps invoke the battle log for this
	}
}
