//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class DamageValue
{
	private Dictionary<DamageType, float> mDmgDict;

	public DamageValue() {
		mDmgDict = new Dictionary<DamageType, float>();
	}

	public float this[DamageType key] {
		get {
			return mDmgDict[key];
		}
		set {
			mDmgDict[key] = value;
		}
	}

	public void MergeAndSum(DamageValue dmgValue) {
		foreach(KeyValuePair<DamageType, float> entry in dmgValue.mDmgDict) {
			if(mDmgDict.ContainsKey(entry.Key)) {
				mDmgDict[entry.Key] = mDmgDict[entry.Key] + entry.Value;
			}
			else {
				mDmgDict[entry.Key] = entry.Value;
			}
		}
		//if(mDmgDict[
	}
}


