//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public interface IBattleEvent
{
	BattleEntity srcEntity {
		get;
	}

	BattleEventType eventType {
		get;
	}

	// TODO remove event text and have it handled within execute
	string  eventText {
		get;
	}

	void Execute();
}

