//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public enum OffensiveModifierType
{
	TOTAL_DMG,
	CRIT_MOD,
	CRIT_TOTAL,
	ARMOR_IGNORE,
	DODGE_IGNORE,
	STR_MOD,
	AGI_MOD,
	DEX_MOD,
	INT_MOD,
	WIS_MOD
}
