// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class StatusEffectEvent : IBattleEvent
{
	public enum StatusEventType {
		NEW,
		REPLACED,
		REMOVED,
		EXPIRED,
	}
	
	public StatusEffectEvent (BattleEntity srcEntity, IStatusEffectExecutor statusEffect, StatusEventType statusEventType) 
	{
		this.SrcEntity = srcEntity;
		this.statusEffect = statusEffect;
		this.statusEventType = statusEventType;
	}

	public BattleEntity SrcEntity {
		private set;
		get;
	}

	public StatusEventType statusEventType {
		private set;
		get;
	}

	public IStatusEffectExecutor statusEffect {
		private set;
		get;
	}

	public BattleEventType EventType {
		get {
			return BattleEventType.STATUS_EFFECT;
		}
	}

	public override string ToString ()
	{
		return string.Format ("[StatusEffectEvent: srcEntity={0}, statusEventType={1}, statusEffect={2}, eventType={3}]", SrcEntity, statusEventType, statusEffect, EventType);
	}
	
}

