//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

[Serializable]
public class ArmorSlot
{
	[SerializeField]
	private ArmorConfig mConfig;
	public ArmorConfig config {
		get { return mConfig; }
	}	

	public ArmorSlot() {}

	public ArmorSlot(ArmorConfig config) {
		mConfig = config;
	}

	public string displayName {
		get { return mConfig.displayName; }
	}

	public ArmorPosition slot {
		get { return mConfig.armorPosition; }
	}

	public ArmorType type {
		get { return mConfig.armorType; }
	}

	public ResistProperties resists {
		get { return mConfig.resists; }
	}
}

