//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ArmorConfig : ScriptableObject
{

	[SerializeField]
	private string mDisplayName = null;
	public string displayName { 
		get { return mDisplayName; }
	}

	[SerializeField]
	private ArmorPosition mArmorPosition = ArmorPosition.TORSO;
	public ArmorPosition armorPosition { 
		get { return mArmorPosition; }
	}

	[SerializeField]
	private ArmorType mArmorType = ArmorType.LIGHT;
	public ArmorType armorType { 
		get { return mArmorType; }
	}

	[SerializeField]
	private ResistProperties mResists = null;
	public ResistProperties resists {
		get { return mResists; }
	}	
}
