//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

[Serializable]
public class WeaponConfig : ScriptableObject
{
	public string weaponName;
	public float baseDamage;
	public OffensiveModifier[] offensiveModifiers;
	public DamageType dmgType;
	public WeaponType weaponType;

	public Texture2D icon;
		
}