//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

[Serializable]
public class WeaponSO : EquipmentSO, IWeapon
{
    public ElementProperties damageMin = new ElementProperties();
    public ElementProperties damageMax = new ElementProperties();

    // weapon scaling
    public AttributeProperties attributeScaling = new AttributeProperties();

    public GameConstants.WeaponHand weaponHand = GameConstants.WeaponHand.MAIN;

	protected override void SanityCheck ()
	{
		base.SanityCheck ();		
	}


	protected override ICombatNode CreateCombatNode ()
	{
		WeaponCombatNode node = new WeaponCombatNode(this);		
		return node;
	}

	// TODO build combat node to pull values from for UI
}