//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class BattleActionFactory
{
	public static BattleAction CreateBattleAction(CombatSkill fromSkill, BattleEntity origin, ITargetResolver targetResolver) {
		switch(fromSkill.combatSkillConfig.combatSkillEnum) {
		case CombatSkillActionEnum.BASIC_FIGHT:		
			return new BattleActionAttack(fromSkill, origin, targetResolver);
		}

		throw new Exception("Unable to find skill: " + fromSkill.combatSkillConfig.displayName + " : " + fromSkill.combatSkillConfig.combatSkillEnum);
	}
}


