//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


public abstract class BattleActionPositive : BattleAction
{
	public BattleActionPositive(CombatSkill skill, BattleEntity source, ITargetResolver targetResolver) : base(skill, source, targetResolver) {

	}

	public PositiveCombatSkill positiveCombatSkill {
		get { return (PositiveCombatSkill) this.combatSkill; }
	}

	public float this[PositiveOffensiveModifierType type] {
		get { return positiveCombatSkill[type]; }
	}
}


