//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


public abstract class BattleActionPhysical : BattleAction
{
	public BattleActionPhysical(CombatSkill skill, BattleEntity source, ITargetResolver targetResolver) : base(skill, source, targetResolver) {

	}

	public PhysicalCombatSkill physicalCombatSkill {
		get { return (PhysicalCombatSkill) this.combatSkill; }
	}

	public float this[PhysicalOffensiveModifierType type] {
		get { return physicalCombatSkill[type]; }
	}
}


