//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;


public abstract class BattleActionMagical : BattleAction
{
	public BattleActionMagical(CombatSkill skill, BattleEntity source, ITargetResolver targetResolver) : base(skill, source, targetResolver) {

	}

	public MagicalCombatSkill magicalCombatSkill {
		get { return (MagicalCombatSkill) this.combatSkill; }
	}

	public float this[MagicalOffensiveModifierType type] {
		get { return magicalCombatSkill[type]; }
	}
}


