//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public abstract class BasicStatusEffect : IStatusEffect
{
	private float mTimeCounter;
	private float mTotalDuration;

	public BasicStatusEffect(float totalDurationLength) {
		mTotalDuration = totalDurationLength;
	}
	
	public void IncrementDurationTime (float timeDelta)
	{
		mTimeCounter += timeDelta;
	}

	public float currentDurationLength {
		get { return mTimeCounter; }
	}

	public float totalDurationLength {
		get { return mTotalDuration; }
	}

	public abstract string GetTextOnAttach (BattleEntity entity);

	public abstract string GetTextOnDettach (BattleEntity entity);

	public abstract string statusName {
		get;
	}

	public abstract string statusKey {
		get;
	}

	public abstract EffectSourceType sourceType {
		get;
	}

	public abstract EffectType effectType {
		get;
	}

	public abstract bool isDispellable {
		get;
	}

	public abstract bool isCurable {
		get;
	}
}


