//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

/// <summary>
/// Combat property status effect. 
/// </summary>
public class CombatPropertyStatusEffectExecutor : SOStatusEffectExecutor
{
	private ICombatNode mCachedNode;

	public CombatPropertyStatusEffectExecutor (StatusEffectSO so) : base(so)
	{

	}

	public ICombatNode CreateCombatNode() {
		if(mCachedNode == null) {
			mCachedNode = new StatusEffectCombatNode(this);
		}
		return mCachedNode;
	}
}
