//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public abstract class SOStatusEffectExecutor : IStatusEffectExecutor
{
	private float mTimeCounter;
	private StatusEffectSO mStatusEffectSO;

	public SOStatusEffectExecutor(StatusEffectSO so) {
		mStatusEffectSO = so;
	}

	public StatusEffectSO statusEffectSO {
		get { return mStatusEffectSO; }
	}
	
	public void IncrementDurationTime (float timeDelta)
	{
		mTimeCounter += timeDelta;
	}

	public bool isDispellable {
		get { 
			StatusEffectType type = mStatusEffectSO.statusEffectType;
			return type == StatusEffectType.MAGICAL_BUFF || type == StatusEffectType.MAGICAL_DEBUFF;
		}
	}

	public bool isCurable {
		get { 
			StatusEffectType type = mStatusEffectSO.statusEffectType;
			return type == StatusEffectType.MAGICAL_DEBUFF || type == StatusEffectType.PHYSICAL_DEBUFF;
		}
	}

	public StatusEffectGroupSO statusEffectGroup {
		get {
			return mStatusEffectSO.statusEffectGroup;
		}
	}

	public StatusEffectType effectType {
		get {
			return mStatusEffectSO.statusEffectType;
		}
	}

	public StatusEffectType sourceType {
		get {
			return mStatusEffectSO.statusEffectType;
		}
	}

	public float totalDurationLength {
		get {
			return mStatusEffectSO.duration;
		}
	}

	public float currentDurationLength {
		get {
			return mTimeCounter;
		}
	}

	public bool isExpired {
		get {
			return mTimeCounter >= mStatusEffectSO.duration;
		}
	}
}


