//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

/// <summary>
/// StatusEffectGroup, there may be many different instances that cause the same effect. We want to make sure we 
/// associate each instant that shares a group with the same object for sake of asssigning text / graphic information
/// as well as applying multiple buffs of the same type.
/// 
/// </summary>
public class StatusEffectGroupData : ScriptableObject
{
	// IF THIS IS A STAT GROUP, LETS SET IT HERE
	[SerializeField]
	private CombatProperty mCombatProperty = CombatProperty.NONE;
	public CombatProperty combatProperty {
		get { return mCombatProperty; }
	}

	// TODO special case status effect group: 
	// ie: poison, haste, onEvent()

	// ICONS

	/// <summary>
	/// The magical buff icon.
	/// </summary>
	[SerializeField]
	private Texture2D mMagicalBuffIcon;

	[SerializeField]
	private Texture2D mMagicalDebuffIcon;

	[SerializeField]
	private Texture2D mPhysicalDebuffIcon;

	[SerializeField]
	private string mOnMagicalDebuffTextFormat;

	[SerializeField]
	private string mOnPhysicalDebuffTextFormat;

	[SerializeField]
	private string mOnMagicalBuffTextFormat;

	[SerializeField]
	private string mOnCuredTextFormat;

}


