//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class StatusEffectSO : ScriptableObject
{
	[SerializeField]
	private StatusEffectGroupSO mStatusEffectGroup = null;

	[SerializeField]
	private ValueModifier mValueModifier = new ValueModifier();

	[SerializeField]
	private StatusEffectType mStatusEffectType = StatusEffectType.MAGICAL_BUFF;

	[SerializeField]
	private float mDuration = 0;

	public StatusEffectGroupSO statusEffectGroup {
		get {
			return this.mStatusEffectGroup;
		}
	}
	
	public ValueModifier valueModifier {
		get {
			return this.mValueModifier;
		}
	}
	
	public StatusEffectType statusEffectType {
		get {
			return this.mStatusEffectType;
		}
	}
	
	public float duration {
		get {
			return this.mDuration;
		}
	}
}
