// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

[Serializable]
public class StatusEffectRule
{
	/// <summary>
	/// Gets the target.
	/// </summary>
	/// <value>The target.</value>
	public BattleEntity target {
			get;
			private set;
	}

	/// <summary>
	/// Gets the effect.
	/// </summary>
	/// <value>The effect.</value>
	public IStatusEffectExecutor effect {
			get;
			private set;
	}

	/// <summary>
	/// Gets the rule.
	/// </summary>
	/// <value>The rule.</value>
	public StatusEffectHitPredicate rule {
			get;
			private set;
	}

	public StatusEffectRule (IStatusEffectExecutor effect, BattleEntity target, StatusEffectHitPredicate rule) {	
		this.effect = effect;
		this.target = target;
		this.rule = rule;
	}

	// Rules to determine when the effect should be proccessed
	public enum StatusEffectHitPredicate {
		ALWAYS,
		ON_HIT,
		ON_MISS
	}
}