//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class OffensiveCombatModifierNode : IOffensivePhysicalCombatModifier, IOffensiveMagicalCombatModifier
{
	private List<IOffensivePhysicalCombatModifier> children;

	public OffensiveCombatModifierNode ()
	{
		children = new List<IOffensivePhysicalCombatModifier>();
	}

	public float powerPhysicalAdd {
		get {
			float total = 0;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total += mod.powerPhysicalAdd;
			}
			return total;
		}
	}

	public float powerPhysicalMultiply {
		get {
			float total = 1;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total *= mod.powerPhysicalMultiply;
			}
			return total;
		}
	}

	public float totalDamageAdd {
		get {
			float total = 0;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total += mod.totalDamageAdd;
			}
			return total;
		}
	}

	public float totalDamageMultiply {
		get {
			float total = 1;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total *= mod.totalDamageMultiply;
			}
			return total;
		}
	}

	public float critChanceAdd {
		get {
			float total = 0;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total += mod.critChanceAdd;
			}
			return total;
		}
	}

	public float critChanceMultiply {
		get {
			float total = 1;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total *= mod.critChanceMultiply;
			}
			return total;
		}
	}

	public float armorIgnoreAdd {
		get {
			float total = 0;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total += mod.armorIgnoreAdd;
			}
			return total;
		}
	}

	public float armorIgnoreMultiply {
		get {
			float total = 1;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total *= mod.armorIgnoreMultiply;
			}
			return total;
		}
	}

	public float dodgeIgnoreAdd {
		get {
			float total = 0;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total += mod.dodgeIgnoreAdd;
			}
			return total;
		}
	}

	public float dodgeIgnoreMultiply {
		get {
			float total = 1;
			foreach(IOffensivePhysicalCombatModifier mod in children) {
				total *= mod.dodgeIgnoreMultiply;
			}
			return total;
		}
	}
}


