//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class StatusEffectVocalize : StatusEffectSpellFailure
{
		
	private const string EFFECT_NAME = "Vocalize";


	public StatusEffectVocalize(float modValue, float duration) : base(duration, modValue) {

	}

	public override string GetTextOnAttach (BattleEntity entity)
	{
		return string.Format("{0} feels his/her voice strengthen.");
	}

	public override string GetTextOnDettach (BattleEntity entity)
	{
		return string.Format("{0} feels his/her voice go return to normal.");
	}

	public override StatusEffectType sourceType {
		get {
			return StatusEffectType.MAGICAL_BUFF;
		}
	}

	public override string statusName {
		get {
			return EFFECT_NAME;
		}
	}

	public override bool isCurable {
		get {
			return false;
		}
	}

	public override string statusKey {
		get {
			return StatusEffectHoarse.STATUS_NAME;
		}
	}

	public override bool isDispellable {
		get {
			return true;
		}
	}	
}

